
server:
  port: 8090

spring:
  application:
    name: User-Service
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  properties:
    hibernate:
      dialect: org.hibernate.dialect.PostgreSQLDialect
  repositories:
    enabled: true
  datasource:
    url: jdbc:postgresql://0.0.0.0:5432/postgres
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver